### ISSUE TITLE
Enforcing compile on unix is not necessary (works on windows)

### ISSUE THREAD

**Issue by bjab** [hypfvieh/bluez-dbus#31]
Hi
Thanks for this project!

FYI: project compiles on windows, as there is compile time dependency on unix libraries.

More over, I just sucessfully connected to BLE device from windows by remote connection to dbus ;)

On linux (Raspberry Pi zero W in my case) just run as root:
`socat TCP-LISTEN:5234,reuseaddr,fork UNIX-CLIENT:/var/run/dbus/system_bus_socket`

And on windows you can use:
`DeviceManager.createInstance("tcp:host=192.168.0.xxx,port=5234,family=ipv4");`

**Comment by hypfvieh** [comment]
I know that it can be built and may be used like you described. 
By the way, it is also possible to configure DBus to use TCP natively instead of bridging using socat
(socat my break certain things like filedescriptor passing. But this is not used in bluez afaik).

The intention behind blocking non-unix builds was to show the user/developer that this library is not designed to do any bluetooth stuff on windows natively. 
It relies on dbus and the bluez library. Neither bluez nor Dbus (except of dbus-java) provide a implementation for windows.
